version: 0.0
os: linux
files:
  - source: ./
    destination: /opt/creative_info_manager/
hooks:
  BeforeInstall:
    - location: code_deploy_scripts/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: code_deploy_scripts/after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: code_deploy_scripts/application_start.sh
      timeout: 30
      runas: root
  ValidateServie:
    - location: code_deploy_scripts/validate_service.sh
      timeout: 30
      runas: root
